### ISSUE TITLE
The dataset does not include annotation

### ISSUE THREAD

**Issue by hungnguyent** [elnino9ykl/ZJU-Dataset#1]
After downloading dataset in google drive and extracting it, I only see 6 videos driving scence as below:

![image](https://user-images.githubusercontent.com/64905330/82857323-db09e600-9f3a-11ea-8a20-8dec866bd5a2.png)

There is no semantic segmentation mask at all. Would you please upload it?

**Comment by elnino9ykl** [comment]
Hi,
   thank you for your question.
   Yes, this dataset does not include annotations. As you can see in our papers, we use this dataset to produce a day-night converter and perform qualitative analysis. Quantitative analyses are performed on other datasets.
